name: ci-cd-workflow
on: [workflow_dispatch, push]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install prerequisites and dependencies
        uses: ./.github/actions/install

      - name: Check formatting
        run: npm run prettier

      - name: Check types
        run: npm run typecheck

      - name: Check linting
        run: npm run lint

      - name: Execute tests
        run: npm run test

      - name: Execute build
        run: npm run build

      - name: Upload dist as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  release-job:
    needs: ci-pipeline
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Custom action which creates a release on main pushes
        run: echo "Hello World - create release"

  cd-pipeline:
    needs: [ci-pipeline, release-job]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      pages-url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output env url
        run: echo ${{ env.url }}

  smoke-test:
    if: false
    needs: cd-pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        browser: [firefox, chromium]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install prerequisites and dependencies
        uses: ./.github/actions/install

      - name: Install Playwright Browsers
        run: npx playwright install ${{ matrix.browser }}

      - name: Run Playwright tests
        run: npx playwright test --project ${{ matrix.browser }}
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.cd-pipeline.outputs.pages-url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 1
